<div class="modal fade" id="addmodal" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-xl modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Adicionar colaborador</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="form_cadastro" @submit.prevent="createEmployee(event)">
                <div class="modal-body">                
                    <div class="row">
                        <div class="col-12">                            
                            <span class="text-info">
                                <strong>Nome do Colaborador(a)</strong>
                            </span>
                            <input type="text" name="nome" class="form-control" placeholder="Insira o nome do colaborador(a)" />
                        </div>
                    </div>
                    <ul>
                        <li v-for="dia in weekdays" class="mt-10">
                            <span class="text-info">
                                <strong>{{ dia }}</strong>
                            </span>
                            <div class="row">
                                <div class="col-12">
                                    <div class="row">
                                        <div class="col">
                                            <small><strong>Hora Inicio</strong></small>                                    
                                            <input type="time" :name="`${dia.toLowerCase()}[hora_inicial]`" value="00:00" class="form-control" />
                                        </div>
                                        <div class="col">
                                            <small><strong>Intervalo Inicio</strong></small>                                    
                                            <input type="time" :name="`${dia.toLowerCase()}[intervalo_inicial]`" value="00:00" class="form-control" />
                                        </div>
                                        <div class="col">
                                            <small><strong>Intervalo Fim</strong></small>                                    
                                            <input type="time" :name="`${dia.toLowerCase()}[intervalo_final]`" value="00:00" class="form-control" />
                                        </div>
                                        <div class="col">
                                            <small><strong>Hora Fim</strong></small>                                    
                                            <input type="time" :name="`${dia.toLowerCase()}[hora_final]`" value="00:00" class="form-control" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </li>
                    </ul>                
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-success">
                        <i class="fas fa-check"></i>
                        Cadastrar
                    </button>
                    <button type="button" @click="resetForm" class="btn btn-danger" data-dismiss="modal">
                        <i class="fas fa-times"></i>
                        Cancelar
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>