<div class="container" id="empresa">
    <h3 class="page-title">Painel da Empresa</h3>
    <div class="panel shadow-sm border">
        <div class="row">
            <div class="col-sm-12 col-md-6">
                <ul class="list-group">
                    <li class="list-group-item" v-for="(colaborador, index) in employees">
                        <div class="row">
                            <div class="col-9">
                                <h5><strong>{{ colaborador.nome }}</strong></h5>
                            </div>
                            <div class="col-3">
                                <a data-toggle="collapse" :href="`#colaborador${index}`" role="button" aria-expanded="false" :aria-controls="`colaborador${index}`">Detalhes</a>
                            </div>
                        </div>
                        <div class="collapse" :id="`colaborador${index}`">
                            <ul>
                                <li v-for="expediente in colaborador.time" class="mt-10">                                
                                    <span class="text-info"><strong>{{ expediente.dia_semana }}</strong></span>
                                    <div class="row">                                    
                                        <div class="col-12">
                                            <div class="row">
                                                <div class="col">
                                                    <small>Hora Inicio</small>
                                                    <input type="time" class="form-control" :value="expediente.hora_inicial" />
                                                </div>
                                                <div class="col">
                                                    <small>Intervalo Inicio</small>
                                                    <input type="time" class="form-control" :value="expediente.intervalo_inicial" />
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-12">
                                            <div class="row">
                                                <div class="col">
                                                    <small>Intervalo Fim</small>
                                                    <input type="time" class="form-control" :value="expediente.intervalo_final" />
                                                </div>
                                                <div class="col">
                                                    <small>Hora Fim</small>
                                                    <input type="time" class="form-control" :value="expediente.hora_final" />
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <hr />                                
                                </li>
                            </ul>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 col-md-6">

            </div>
        </div>
    </div>
</div>
<?php
    requer(['empresa']);
?>