<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">        
        <link rel="stylesheet" href="/assets/css/bootstrap/bootstrap.min.css" />
        <link rel="stylesheet" href="/assets/css/icons/fontawesome/all.min.css" />        
        <link rel="stylesheet" href="/assets/css/system/main.css" />
        <script type="text/javascript" src="/assets/js/jquery/jquery.min.js"></script>
        <script type="text/javascript" src="/assets/js/bootstrap/bootstrap.bundle.min.js"></script>
        <script type="text/javascript" src="/assets/js/system/main.js"></script>
        <script type="text/javascript" src="/assets/js/vue/vue.js"></script>
        <script type="text/javascript" src="/assets/js/axios/axios.min.js"></script>
    </head>
    <body>
        <div ref="loading" id="loading">
            <img src="/assets/images/loader.gif" />
        </div>
        <div class="row">
            <div class="col-sm-12 shadow-sm">
                <div class="container">            
                    <img src="/assets/images/s3nd-logo.png" alt="s3nd logo"/>
                </div>
            </div>
        </div>
        
        